# Generated by Django 2.1.2 on 2018-10-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumupload',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Select an album to add these images to. leave this empty to create a new album from the supplied title.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.IMAGESTORE_ALBUM_MODEL),
        ),
        migrations.AlterField(
            model_name='albumupload',
            name='zip_file',
            field=models.FileField(help_text='Select a .zip file of images to upload into a new Gallery.', upload_to='temp/', verbose_name='images file (.zip)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.IMAGESTORE_ALBUM_MODEL, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]